# Generated by Django 5.2.1 on 2025-05-12 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('origem', models.CharField(max_length=80)),
                ('destino', models.CharField(max_length=80)),
                ('data_hora_partida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pro', 'Programado'), ('emb', 'Embarque'), ('con', 'Concluído')], max_length=3)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flights.gate')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('status_checkin', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], max_length=7)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='flights.flight')),
            ],
        ),
    ]
