# Generated by Django 5.2.1 on 2025-05-12 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger_checkin_alter_flight_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger', to='flights.flight'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='status_checkin',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=7),
        ),
    ]
