# Generated by Django 5.2.1 on 2025-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_passenger_flight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
